apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
  annotations:
    policies.kyverno.io/title: Require requests and limits
    policies.kyverno.io/category: baseline
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: requests-and-limits-required
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
      validate:
        message: CPU and memory requests and limits are required for all containers.
        foreach:
          - list: request.object.spec.containers[]
            pattern:
              resources:
                requests:
                  cpu: "?*"
                  memory: "?*"
                limits:
                  cpu: "?*"
                  memory: "?*"
          - list: request.object.spec.initContainers[] || []
            pattern:
              resources:
                requests:
                  cpu: "?*"
                  memory: "?*"
                limits:
                  cpu: "?*"
                  memory: "?*"

